# coding: utf-8
# AUTOGENERATED BY gen_script.sh from 
# Copyright (C) Nyimbi Odero, Mon Oct 23 11:04:30 UTC 2017
 
from sqlalchemy_continuum import make_versioned
from sqlalchemy import func
from flask_appbuilder import Model
from flask_appbuilder.models.mixins import AuditMixin, FileColumn, ImageColumn, UserExtensionMixin 
from flask_appbuilder.models.decorators import renders
from flask_appbuilder.filemanager import ImageManager
from sqlalchemy_utils import aggregated, force_auto_coercion, observes
from sqlalchemy.orm import relationship, query, defer, deferred, column_property
# IMPORT Postgresql Specific Types 
from sqlalchemy.dialects.postgresql import ( 
    ARRAY, BIGINT, BIT, BOOLEAN, BYTEA, CHAR, CIDR, DATE,  
    DOUBLE_PRECISION, ENUM, FLOAT, HSTORE, INET, INTEGER,  
    INTERVAL, JSON, JSONB, MACADDR, NUMERIC, OID, REAL, SMALLINT, TEXT,  
    TIME, TIMESTAMP, UUID, VARCHAR, INT4RANGE, INT8RANGE, NUMRANGE,  
    DATERANGE, TSRANGE, TSTZRANGE, TSVECTOR )
from sqlalchemy.dialects.postgresql import aggregate_order_by
from flask_validator import Validator

from sqlalchemy import (Column, Integer, String, ForeignKey,
	Sequence, Float, Text, BigInteger, Date,
	DateTime, Time, Boolean, Index, CheckConstraint,
	UniqueConstraint,ForeignKeyConstraint, Numeric, LargeBinary , Table)
from datetime import timedelta, datetime, date
from sqlalchemy.dialects.postgresql import *
from sqlalchemy_mixins import AllFeaturesMixin
from sqlalchemy.sql import func
from .mixins import *
# How to do validations in a model

		#@classmethod
		#def __declare_last__(cls):
			#ValidateString(User.name)
			#ValidateInteger(User.code)
			#ValidateEmail(User.email, true, true, The e-mail is not valid. Please check it)

# Here is how to extend the User model
#class UserExtended(Model, UserExtensionMixin):
#    contact_group_id = Column(Integer, ForeignKey('contact_group.id'), nullable=True)
#    contact_group = relationship('ContactGroup')


# UTILITY CLASSES

import arrow, enum, datetime
import enum
# Initialize sqlalchemy_utils 
#force_auto_coercion()
#make versioned copies of all tables
#make_versioned()
# Here is how to extend the User model
#class UserExtended(Model, UserExtensionMixin):
#    contact_group_id = Column(Integer, ForeignKey('contact_group.id'), nullable=True)
#    contact_group = relationship('ContactGroup')


# UTILITY CLASSES

import arrow, enum, datetime
import enum
# Initialize sqlalchemy_utils 
#force_auto_coercion()
#make versioned copies of all tables
#make_versioned()
# Here is how to extend the User model
#class UserExtended(Model, UserExtensionMixin):
#    contact_group_id = Column(Integer, ForeignKey('contact_group.id'), nullable=True)
#    contact_group = relationship('ContactGroup')


# UTILITY CLASSES

import arrow, enum, datetime
import enum
# Initialize sqlalchemy_utils 
#force_auto_coercion()
#make versioned copies of all tables
#make_versioned()
